---
functional:
  - Пользователь должен иметь возможность регистрации на сайте.
  - Пользователь должен иметь возможность авторизации на сайте.
  - Пользователь должен иметь возможность просмотра архивных батлов.
  - Пользователь должен иметь возможность просмотра текущего баттла наблюдателем в режиме online.
  - Пользователь должен иметь возможность выбора языка программирования в терминале батла.
  - Пользователь должен иметь возможность выбора в терминале батла локации странички (русский и английский).
non-functional:
  - Сайт должен быть удобен для использования.
  - Сайт должен защищать данные пользователя от изменений.
  - Сайт должен быть совместим с последними версиями браузеров Google Chrome, Firefox, Microsoft Edge, Safari.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть оптимизирован для скорости работы в режиме батла.
implicit:
  - Участники батла не могут вводить и редактировать код в терминале соперника.
  - Наблюдатели не могут вводить и редактировать код в терминале участников батла.
  - Отображение элементов сайта не должно искажаться в разных локациях (русский и английский).
